### ISSUE TITLE
ref_viruses_rep_genomes extraction failure

### ISSUE THREAD

**Issue by kislyuk** [taxoniq/taxoniq#22]
```
INFO:__main__:Processing BLAST db volume /mnt/blastdb/ref_viruses_rep_genomes
Error: [blastdbcmd] error while reading seqid
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/andrey.kislyuk/taxoniq/taxoniq/build.py", line 484, in <module>
    build_trees(blast_databases=[db.name for db in BLASTDatabase if db.name not in {"nt", "nr"}])
  File "/home/andrey.kislyuk/taxoniq/taxoniq/build.py", line 265, in build_trees
    for acc_info in preprocess_accession_data(blast_databases, taxid2refrep=taxid2refrep):
  File "/home/andrey.kislyuk/taxoniq/taxoniq/build.py", line 170, in preprocess_accession_data
    for accession_id, accession_info in load_accession_info_from_blast_db(blast_db_name):
  File "/home/andrey.kislyuk/taxoniq/taxoniq/build.py", line 430, in load_accession_info_from_blast_db
    for line in subprocess.check_output(blastdbcmd).decode().splitlines():
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['blastdbcmd', '-db', 'ref_viruses_rep_genomes', '-entry', 'all', '-outfmt', '%a %o %l %T']' returned non-zero exit status 1.
make: *** [Makefile:31: build] Error 1
andrey.kislyuk@akislyuk-rnd:~/taxoniq$ 
```

**Comment by kislyuk** [comment]
```
Error: [blastdbcmd] error while reading seqid
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/andrey.kislyuk/taxoniq/taxoniq/build.py", line 484, in <module>
    build_trees(blast_databases=[db.name for db in BLASTDatabase if db.name not in {"nt", "nr"}])
  File "/home/andrey.kislyuk/taxoniq/taxoniq/build.py", line 265, in build_trees
    for acc_info in preprocess_accession_data(blast_databases, taxid2refrep=taxid2refrep):
  File "/home/andrey.kislyuk/taxoniq/taxoniq/build.py", line 170, in preprocess_accession_data
    for accession_id, accession_info in load_accession_info_from_blast_db(blast_db_name):
  File "/home/andrey.kislyuk/taxoniq/taxoniq/build.py", line 430, in load_accession_info_from_blast_db
    for line in subprocess.check_output(blastdbcmd).decode().splitlines():
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['blastdbcmd', '-db', 'ref_prok_rep_genomes.00', '-entry', 'all', '-outfmt', '%a %o %l %T']' returned non-zero exit status 1.

```

**Comment by kislyuk** [comment]
Using the most recent ncbi-blast+ distribution fixes this.
